version: "3.8"

services:
    kanban-backend:
        restart: always
        ports:
            - "7000:8000"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            # Use . for current directory if unsure, or ensure $LARAVEL_PROJECT_PATH is correct
            - .:/var/www
        env_file:
            - ./.env
        user: "${UID}:${GID}"
