apiVersion: v1
kind: Service
metadata:
  name: kanban-backend-service
spec:
  selector:
    app: kanban-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30044
  type: NodePort
